export default [
 {
   "Date": "2-May",
   "Event": "WCC Women’s ride",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Beginners": "",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "6:30",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "2-May",
   "Event": "Pathway Riders Coffee Meetup",
   "Kids": "",
   "Adults": "",
   "Women": "x",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "3-May",
   "Event": "Bike Month Kickoff",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "x",
   "Time": "6:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "4-May",
   "Event": "Social Ride",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Beginners": "x",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "7:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "4-May",
   "Event": "TXTRI Village Ride",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "x",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "9:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "5-May",
   "Event": "Kids Ride ages 4-10",
   "Kids": "x",
   "Adults": "",
   "Women": "",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "5:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "6-May",
   "Event": "Bikeland Trail Ride",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "x",
   "Long road": "",
   "Workshop": "",
   "Time": "8:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "7-May",
   "Event": "WCC 30 mile ride",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "",
   "Long road": "x",
   "Workshop": "",
   "Time": "7:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "7-May",
   "Event": "Public Art Ride",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Beginners": "x",
   "Pathway": "X",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "2:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "x",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "8-May",
   "Event": "Sun and Ski Trail Ride",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "x",
   "Long road": "",
   "Workshop": "",
   "Time": "6:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "9-May",
   "Event": "Pathway Riders Coffee Meetup",
   "Kids": "",
   "Adults": "",
   "Women": "x",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "10-May",
   "Event": "Maintenance workshop",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "x",
   "Time": "7:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "10-May",
   "Event": "WCC Relaxed ride",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "x",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "6:30",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "11-May",
   "Event": "TXTRI Village Ride",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "x",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "9:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "12-May",
   "Event": "Bike Kayak Bike",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "x",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "9:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "12-May",
   "Event": "55+ Moonlight ride",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "x",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "13-May",
   "Event": "Ghorba workshop",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "x",
   "Long road": "",
   "Workshop": "x",
   "Time": "10:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "13-May",
   "Event": "Kids Rodeo",
   "Kids": "x",
   "Adults": "",
   "Women": "",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "13-May",
   "Event": "Neighborhood rides",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Beginners": "x",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "13-May",
   "Event": "Swap Meet",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "x",
   "Time": "8:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "14-May",
   "Event": "Mother's Day ride",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "16-May",
   "Event": "Women’s Ride",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Beginners": "",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "9:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "16-May",
   "Event": "Pathway Riders Coffee Meetup",
   "Kids": "",
   "Adults": "",
   "Women": "x",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "17-May",
   "Event": "Food for Cycling",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "x",
   "Time": "6:30",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "17-May",
   "Event": "WCC Relaxed ride",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "x",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "6:30",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "18-May",
   "Event": "Social Ride",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Beginners": "x",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "7:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "18-May",
   "Event": "TXTRI Village Ride",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "x",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "9:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "19-May",
   "Event": "Bike to Work Day",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "x",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "6:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "20-May",
   "Event": "Sun&Ski Relaxed road ride",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "x",
   "Pathway": "",
   "Road": "x",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "9:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "20-May",
   "Event": "Kids ride",
   "Kids": "x",
   "Adults": "",
   "Women": "",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "10:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "20-May",
   "Event": "Bike Kayak Bike",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "x",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:15",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "20-May",
   "Event": "Bike ART",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "21-May",
   "Event": "Public Art Ride",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Beginners": "x",
   "Pathway": "X",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "2:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "x",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "23-May",
   "Event": "Pathway Riders Coffee Meetup",
   "Kids": "",
   "Adults": "",
   "Women": "x",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "24-May",
   "Event": "Maintenance workshop",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "x",
   "Time": "7:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "24-May",
   "Event": "WCC Relaxed ride",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "x",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "6:30",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "25-May",
   "Event": "TXTRI Village Ride",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "x",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "9:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "26-May",
   "Event": "Bike ride - 10-15 yrs",
   "Kids": "X",
   "Adults": "",
   "Women": "",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "5:00",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "27-May",
   "Event": "WCC Whole Foods ride",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "7:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "x"
 },
 {
   "Date": "29-May",
   "Event": "Bikeland Memorial Day Ride",
   "Kids": "",
   "Adults": "x",
   "Women": "",
   "Beginners": "",
   "Pathway": "",
   "Road": "",
   "Off road": "",
   "Long road": "x",
   "Workshop": "",
   "Time": "8:00",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "30-May",
   "Event": "Pathway Riders Coffee Meetup",
   "Kids": "",
   "Adults": "",
   "Women": "x",
   "Beginners": "",
   "Pathway": "x",
   "Road": "",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "8:30",
   "timeOfDay": "am",
   "Morning": "x",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "x",
   "Weekend": ""
 },
 {
   "Date": "31-May",
   "Event": "WCC Relaxed ride",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Beginners": "x",
   "Pathway": "",
   "Road": "X",
   "Off road": "",
   "Long road": "",
   "Workshop": "",
   "Time": "6:30",
   "timeOfDay": "pm",
   "Morning": "",
   "Afternoon": "",
   "Evening": "x",
   "Weekday": "x",
   "Weekend": ""
 }
]