export default [
 {
   "Date": "2-May",
   "Time": "6:30pm",
   "Event": "WCC Women’s ride",
   "Starting point": "Whole Foods",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "2-May",
   "Time": "8:30am",
   "Event": "Pathway Riders Ride",
   "Starting point": "Panther Creek, near Randall's",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "2-May",
   "Time": "6:00pm",
   "Event": "Bicycle World Basic Maint. Wkshp",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "3-May",
   "Time": "6:00pm",
   "Event": "Bike Month Kickoff",
   "Starting point": "Whole Foods",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "4-May",
   "Time": "7:00pm",
   "Event": "Social Ride",
   "Starting point": "Torchy’s",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "X",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "4-May",
   "Time": " 9am",
   "Event": "TXTRI Village Ride",
   "Starting point": "Panther Creek Starbucks",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "5-May",
   "Time": "5:00pm",
   "Event": "Kids Ride ages 4-10",
   "Starting point": "Rob Fleming Lodge",
   "Kids": "X",
   "Adults": "",
   "Women": "",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "X",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "X",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "6-May",
   "Time": "8:30am",
   "Event": "Bikeland Trail Ride",
   "Starting point": "Rob Fleming Park",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "X",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "X",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "6-May",
   "Time": "10:00am",
   "Event": "Bicycle World Bike Wash",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "7-May",
   "Time": "2:00pm",
   "Event": "Public Art Ride",
   "Starting point": "South Regional Library",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "X",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "7-May",
   "Time": "8:00am",
   "Event": "Bicycle World Road Ride",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "8-May",
   "Time": "6:00pm",
   "Event": "Sun and Ski Trail Ride",
   "Starting point": "Rob Fleming Park",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "X",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "X",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "9-May",
   "Time": "8:30am",
   "Event": "Pathway Riders Ride",
   "Starting point": "Panther Creek, near Randall's",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "9-May",
   "Time": "6:00pm",
   "Event": "Bicycle World Adv Maint. Wkshp",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "10-May",
   "Time": "7:00pm",
   "Event": "Maintenance workshop",
   "Starting point": "Whole Foods",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "10-May",
   "Time": "6:30pm",
   "Event": "WCC Relaxed ride",
   "Starting point": "Terramont Park",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "X",
   "Town Center": ""
 },
 {
   "Date": "11-May",
   "Time": " 9am",
   "Event": "TXTRI Village Ride",
   "Starting point": "Alden Bridge -- in front of sculpture",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "12-May",
   "Time": "8:00pm",
   "Event": "55+ Moonlight ride",
   "Starting point": "Township parking lot",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "X",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "12-May",
   "Time": "9:00am",
   "Event": "Bike Kayak Bike",
   "Starting point": "Shadowbend Park",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "X",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "13-May",
   "Time": "8:00am",
   "Event": "Neighborhood ride",
   "Starting point": "Bear Branch Park",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Families": "X",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "X",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "13-May",
   "Time": "8:00am",
   "Event": "Neighborhood ride",
   "Starting point": "Ridgewood Park",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Families": "X",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "13-May",
   "Time": "8:00am",
   "Event": "Swap Meet",
   "Starting point": "Grogans Mill Farmers Mkt",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "X",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "13-May",
   "Time": "8:30am",
   "Event": "Kids Rodeo",
   "Starting point": "Recreation center Creekside/old YMCA",
   "Kids": "X",
   "Adults": "",
   "Women": "",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "X",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "13-May",
   "Time": "8:00am",
   "Event": "Neighborhood ride",
   "Starting point": "Tupelo Park",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Families": "X",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "X",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "13-May",
   "Time": "10:00am",
   "Event": "GHORBA Mountain Bike Clinic ",
   "Starting point": "Terramont Park",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "X",
   "Town Center": ""
 },
 {
   "Date": "13-May",
   "Time": "10:00am",
   "Event": "Bicycle World Bike Wash",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "13-May",
   "Time": "8:00am",
   "Event": "Neighborhood ride",
   "Starting point": "May Valley Park",
   "Kids": "",
   "Adults": "",
   "Women": "",
   "Families": "X",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "X",
   "Town Center": ""
 },
 {
   "Date": "14-May",
   "Time": "8:30am",
   "Event": "Mother's Day ride",
   "Starting point": "Whole Foods",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "14-May",
   "Time": "8:00am",
   "Event": "Bicycle World Road Ride",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "16-May",
   "Time": "8:30am",
   "Event": "Pathway Riders Ride",
   "Starting point": "Panther Creek, near Randall's",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "16-May",
   "Time": " 9am",
   "Event": "Women’s Ride",
   "Starting point": "Sterling Ridge Amici Café",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "X",
   "Town Center": ""
 },
 {
   "Date": "16-May",
   "Time": "6:00pm",
   "Event": "Bicycle World Basic Maint. Wkshp",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "17-May",
   "Time": "6:30pm",
   "Event": "WCC Relaxed ride",
   "Starting point": "Terramont Park",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "X",
   "Town Center": ""
 },
 {
   "Date": "17-May",
   "Time": "6:30pm",
   "Event": "Nutrition for Cycling",
   "Starting point": "Huti's 5",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "18-May",
   "Time": "7:00pm",
   "Event": "Social Ride",
   "Starting point": "Bar Louie",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "X",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "18-May",
   "Time": " 9am",
   "Event": "TXTRI Village Ride",
   "Starting point": "Creekside  Rob Fleming Park",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "X",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "19-May",
   "Time": "6:30-9am",
   "Event": "Bike to Work Day",
   "Starting point": "Whole Foods, Black Walnut",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "20-May",
   "Time": "8:00pm",
   "Event": "Bike ART ride",
   "Starting point": "Near Whole Foods",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "20-May",
   "Time": "8:15am",
   "Event": "Bike Kayak Bike",
   "Starting point": "Hughes Landing",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "20-May",
   "Time": "10:30am",
   "Event": "Kids ride",
   "Starting point": "Hughes Landing",
   "Kids": "X",
   "Adults": "",
   "Women": "",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "20-May",
   "Time": "9:00am",
   "Event": "Sun&Ski Relaxed road ride",
   "Starting point": "Hughes Landing",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "X",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "20-May",
   "Time": "9:30am",
   "Event": "Women's MtnBike ride",
   "Starting point": "Flintridge TrailHead",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "X",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "X",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "20-May",
   "Time": "10:00am",
   "Event": "Bicycle World Bike Wash",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "21-May",
   "Time": "2:00pm",
   "Event": "Public Art Ride",
   "Starting point": "South Regional Library",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "X",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "21-May",
   "Time": "8:00am",
   "Event": "Bicycle World Road Ride",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "23-May",
   "Time": "8:30am",
   "Event": "Pathway Riders Ride",
   "Starting point": "Panther Creek, near Randall's",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "23-May",
   "Time": "6:00pm",
   "Event": "Bicycle World Adv Maint. Wkshp",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "24-May",
   "Time": "7:00pm",
   "Event": "Maintenance workshop",
   "Starting point": "Whole Foods",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "24-May",
   "Time": "6:30pm",
   "Event": "WCC Relaxed ride",
   "Starting point": "Terramont Park",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "X",
   "Town Center": ""
 },
 {
   "Date": "25-May",
   "Time": " 9am",
   "Event": "TXTRI Village Ride",
   "Starting point": "Sterling Ridge Amici Café",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "X",
   "Town Center": ""
 },
 {
   "Date": "26-May",
   "Time": "5:00pm",
   "Event": "Bike ride - 10-15 yrs",
   "Starting point": "Rob Fleming Lodge",
   "Kids": "X",
   "Adults": "",
   "Women": "",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "X",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "X",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "27-May",
   "Time": "7:30am",
   "Event": "WCC Whole Foods ride",
   "Starting point": "Whole Foods",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "27-May",
   "Time": "10:00am",
   "Event": "Bicycle World Bike Wash",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "28-May",
   "Time": "8:00am",
   "Event": "Bicycle World Road Ride",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "",
   "Weekend": "X",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "29-May",
   "Time": "8:00am",
   "Event": "Bikeland Memorial Day Ride",
   "Starting point": "Whole Foods",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "X",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": "X"
 },
 {
   "Date": "30-May",
   "Time": "8:30am",
   "Event": "Pathway Riders Ride",
   "Starting point": "Panther Creek, near Randall's",
   "Kids": "",
   "Adults": "",
   "Women": "X",
   "Families": "",
   "Pathway": "X",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "X",
   "Afternoon": "",
   "Evening": "",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "X",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "30-May",
   "Time": "6:00pm",
   "Event": "Bicycle World Basic Maint. Wkshp",
   "Starting point": "Bicycle World",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "X",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "X",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "",
   "Town Center": ""
 },
 {
   "Date": "31-May",
   "Time": "6:30pm",
   "Event": "WCC Relaxed ride",
   "Starting point": "Terramont Park",
   "Kids": "",
   "Adults": "X",
   "Women": "",
   "Families": "",
   "Pathway": "",
   "Road": "X",
   "Road, Relaxed": "",
   "Off road": "",
   "Long Road": "",
   "Workshop": "",
   "Morning": "",
   "Afternoon": "",
   "Evening": "X",
   "Weekday": "X",
   "Weekend": "",
   "Alden Bridge": "",
   "Cochrans  Crossing": "",
   "Creekside": "",
   "Grogans Mill": "",
   "Indian Springs": "",
   "Panther Creek": "",
   "Sterling Ridge": "X",
   "Town Center": ""
 }
];













// V1 data
// export default [
//  {
//    "Date": "2-May",
//    "Event": "WCC Women’s ride",
//    "Kids": "",
//    "Adults": "",
//    "Women": "X",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "6:30",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "2-May",
//    "Event": "Pathway Riders Coffee Meetup",
//    "Kids": "",
//    "Adults": "",
//    "Women": "x",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "3-May",
//    "Event": "Bike Month Kickoff",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "x",
//    "Time": "6:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "4-May",
//    "Event": "Social Ride",
//    "Kids": "",
//    "Adults": "X",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "7:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "4-May",
//    "Event": "TXTRI Village Ride",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "x",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "9:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "5-May",
//    "Event": "Kids Ride ages 4-10",
//    "Kids": "x",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "5:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "6-May",
//    "Event": "Bikeland Trail Ride",
//    "Kids": "",
//    "Adults": "X",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "x",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "7-May",
//    "Event": "WCC 30 mile ride",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "",
//    "Long road": "x",
//    "Workshop": "",
//    "Time": "7:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "7-May",
//    "Event": "Public Art Ride",
//    "Kids": "",
//    "Adults": "X",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "X",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "2:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "x",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "8-May",
//    "Event": "Sun and Ski Trail Ride",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "x",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "6:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "9-May",
//    "Event": "Pathway Riders Coffee Meetup",
//    "Kids": "",
//    "Adults": "",
//    "Women": "x",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "10-May",
//    "Event": "Maintenance workshop",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "x",
//    "Time": "7:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "10-May",
//    "Event": "WCC Relaxed ride",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "6:30",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "11-May",
//    "Event": "TXTRI Village Ride",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "x",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "9:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "12-May",
//    "Event": "Bike Kayak Bike",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "x",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "9:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "12-May",
//    "Event": "55+ Moonlight ride",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "x",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "13-May",
//    "Event": "Ghorba workshop",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "x",
//    "Long road": "",
//    "Workshop": "x",
//    "Time": "10:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "13-May",
//    "Event": "Kids Rodeo",
//    "Kids": "x",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "13-May",
//    "Event": "Neighborhood rides",
//    "Kids": "",
//    "Adults": "X",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "13-May",
//    "Event": "Swap Meet",
//    "Kids": "",
//    "Adults": "X",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "x",
//    "Time": "8:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "14-May",
//    "Event": "Mother's Day ride",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "16-May",
//    "Event": "Women’s Ride",
//    "Kids": "",
//    "Adults": "",
//    "Women": "X",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "9:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "16-May",
//    "Event": "Pathway Riders Coffee Meetup",
//    "Kids": "",
//    "Adults": "",
//    "Women": "x",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "17-May",
//    "Event": "Food for Cycling",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "x",
//    "Time": "6:30",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "17-May",
//    "Event": "WCC Relaxed ride",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "6:30",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "18-May",
//    "Event": "Social Ride",
//    "Kids": "",
//    "Adults": "X",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "7:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "18-May",
//    "Event": "TXTRI Village Ride",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "x",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "9:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "19-May",
//    "Event": "Bike to Work Day",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "x",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "6:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "20-May",
//    "Event": "Sun&Ski Relaxed road ride",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "",
//    "Road": "x",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "9:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "20-May",
//    "Event": "Kids ride",
//    "Kids": "x",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "10:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "20-May",
//    "Event": "Bike Kayak Bike",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "x",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:15",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "20-May",
//    "Event": "Bike ART",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "21-May",
//    "Event": "Public Art Ride",
//    "Kids": "",
//    "Adults": "X",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "X",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "2:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "x",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "23-May",
//    "Event": "Pathway Riders Coffee Meetup",
//    "Kids": "",
//    "Adults": "",
//    "Women": "x",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "24-May",
//    "Event": "Maintenance workshop",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "x",
//    "Time": "7:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "24-May",
//    "Event": "WCC Relaxed ride",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "6:30",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "25-May",
//    "Event": "TXTRI Village Ride",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "x",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "9:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "26-May",
//    "Event": "Bike ride - 10-15 yrs",
//    "Kids": "X",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "5:00",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "27-May",
//    "Event": "WCC Whole Foods ride",
//    "Kids": "",
//    "Adults": "X",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "7:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "",
//    "Weekend": "x"
//  },
//  {
//    "Date": "29-May",
//    "Event": "Bikeland Memorial Day Ride",
//    "Kids": "",
//    "Adults": "x",
//    "Women": "",
//    "Beginners": "",
//    "Pathway": "",
//    "Road": "",
//    "Off road": "",
//    "Long road": "x",
//    "Workshop": "",
//    "Time": "8:00",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "30-May",
//    "Event": "Pathway Riders Coffee Meetup",
//    "Kids": "",
//    "Adults": "",
//    "Women": "x",
//    "Beginners": "",
//    "Pathway": "x",
//    "Road": "",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "8:30",
//    "timeOfDay": "am",
//    "Morning": "x",
//    "Afternoon": "",
//    "Evening": "",
//    "Weekday": "x",
//    "Weekend": ""
//  },
//  {
//    "Date": "31-May",
//    "Event": "WCC Relaxed ride",
//    "Kids": "",
//    "Adults": "",
//    "Women": "",
//    "Beginners": "x",
//    "Pathway": "",
//    "Road": "X",
//    "Off road": "",
//    "Long road": "",
//    "Workshop": "",
//    "Time": "6:30",
//    "timeOfDay": "pm",
//    "Morning": "",
//    "Afternoon": "",
//    "Evening": "x",
//    "Weekday": "x",
//    "Weekend": ""
//  }
// ]